#!/usr/bin/python
This is a part of the external applets for Cairo-Dock
# Copyright : (C) 2015 by Diego Rubin
# E-mail : rubin.diego@gmail.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# http://www.gnu.org/licenses/licenses.html#GPL

####################
### dependancies ###
####################
import sys

try:
    import gtk
except:
    from gi.repository import Gtk as gtk

from CDApplet import *

####################
### Applet class ###
####################
class Applet(CDApplet):
    def __init__(self):
        CDApplet.__init__(self)

    ##### private methods #####

    def show_menu(self):
        pass

    ##### applet definition #####

    def get_config(self,keyfile):
        pass

    def end(self):
        pass

    def begin(self):
        self.icon.SetQuickInfo("uma grande mensagem bem gigante.")

    def reload(self):
        pass

    def on_click(self,iState):
        self.show_menu()

    def on_build_menu(self):
        items = [ { "label": _("Edit Menus"),
                "icon" : "gtk-preferences",
                "id"     : 1 } ]
        self.icon.AddMenuItems(items)

    def on_menu_select(self,iNumEntry):
        if iNumEntry == 1:
            subprocess.Popen("alacarte")

    def on_shortkey(self,key):
        self.show_menu()


if __name__ == '__main__':
    Applet().run()

